/** Tipos de ação gravados em `ordem_servico_logs` pelo módulo de expedição. */
export const LOG_TIPO_EXPEDICAO_DEVOLUCAO = 'EXPEDICAO_DEVOLUCAO_PRODUCAO';
export const LOG_TIPO_EXPEDICAO_CONCLUSAO_SEM_ASSINATURA =
  'EXPEDICAO_CONCLUSAO_SEM_ASSINATURA';
export const LOG_TIPO_EXPEDICAO_OVERRIDE_FINANCEIRO =
  'EXPEDICAO_OVERRIDE_FINANCEIRO';
