export const COMPRAS_PERMISSOES = {
  ACESSAR: 'compras.acessar',
  SOLICITACAO_CRIAR: 'compras.solicitacao.criar',
  SOLICITACAO_APROVAR: 'compras.solicitacao.aprovar',
  PEDIDO_CRIAR: 'compras.pedido.criar',
  PEDIDO_APROVAR: 'compras.pedido.aprovar',
  PEDIDO_ENVIAR: 'compras.pedido.enviar',
  PEDIDO_CANCELAR: 'compras.pedido.cancelar',
  PEDIDO_SUBSTITUIR_FORNECEDOR: 'compras.pedido.substituir_fornecedor',
  RECEBIMENTO_REGISTRAR: 'compras.recebimento.registrar',
  SERVICO_ACEITAR: 'compras.servico.aceitar',
  CONTA_PAGAR_CRIAR: 'compras.conta_pagar.criar',
  PAGAMENTO_REGISTRAR: 'compras.pagamento.registrar',
  PAGAMENTO_ESTORNAR: 'compras.pagamento.estornar',
  AUDITORIA_VISUALIZAR: 'compras.auditoria.visualizar',
} as const;

/** Qualquer permissão operacional de solicitação (ou auditoria). */
export const COMPRAS_PERMISSOES_LEITURA_SOLICITACAO: readonly string[] = [
  COMPRAS_PERMISSOES.SOLICITACAO_CRIAR,
  COMPRAS_PERMISSOES.SOLICITACAO_APROVAR,
  COMPRAS_PERMISSOES.PEDIDO_CRIAR,
  COMPRAS_PERMISSOES.AUDITORIA_VISUALIZAR,
];

/** Qualquer permissão operacional de pedido (ou auditoria). */
export const COMPRAS_PERMISSOES_LEITURA_PEDIDO: readonly string[] = [
  COMPRAS_PERMISSOES.PEDIDO_CRIAR,
  COMPRAS_PERMISSOES.PEDIDO_APROVAR,
  COMPRAS_PERMISSOES.PEDIDO_ENVIAR,
  COMPRAS_PERMISSOES.PEDIDO_CANCELAR,
  COMPRAS_PERMISSOES.PEDIDO_SUBSTITUIR_FORNECEDOR,
  COMPRAS_PERMISSOES.RECEBIMENTO_REGISTRAR,
  COMPRAS_PERMISSOES.SERVICO_ACEITAR,
  COMPRAS_PERMISSOES.CONTA_PAGAR_CRIAR,
  COMPRAS_PERMISSOES.AUDITORIA_VISUALIZAR,
];

export const COMPRAS_PERMISSOES_LEITURA_RECEBIMENTO: readonly string[] = [
  COMPRAS_PERMISSOES.RECEBIMENTO_REGISTRAR,
  COMPRAS_PERMISSOES.PEDIDO_CRIAR,
  COMPRAS_PERMISSOES.PEDIDO_APROVAR,
  COMPRAS_PERMISSOES.AUDITORIA_VISUALIZAR,
];

export const COMPRAS_PERMISSOES_LEITURA_ACEITE: readonly string[] = [
  COMPRAS_PERMISSOES.SERVICO_ACEITAR,
  COMPRAS_PERMISSOES.PEDIDO_CRIAR,
  COMPRAS_PERMISSOES.PEDIDO_APROVAR,
  COMPRAS_PERMISSOES.AUDITORIA_VISUALIZAR,
];

/** Contas a pagar / pagamentos (leitura). */
export const COMPRAS_PERMISSOES_LEITURA_CONTA_PAGAR: readonly string[] = [
  COMPRAS_PERMISSOES.CONTA_PAGAR_CRIAR,
  COMPRAS_PERMISSOES.PAGAMENTO_REGISTRAR,
  COMPRAS_PERMISSOES.PAGAMENTO_ESTORNAR,
  COMPRAS_PERMISSOES.AUDITORIA_VISUALIZAR,
];
