import {
  Building2,
  LayoutDashboard,
  Package,
  Palette,
  Plug,
  Shield,
  Tag,
  Users,
  Wrench,
} from 'lucide-react';
import type { ModuleNavConfig } from './types';

export const configuracoesModuleNav: ModuleNavConfig = {
  id: 'configuracoes',
  label: 'Configurações',
  homeHref: '/configuracoes',
  items: [
    {
      id: 'visao-geral',
      label: 'Visão geral',
      shortLabel: 'Geral',
      href: '/configuracoes',
      description: 'Configurações do sistema.',
      icon: LayoutDashboard,
    },
    {
      id: 'categorias',
      label: 'Categorias de insumos',
      shortLabel: 'Categorias',
      href: '/configuracoes/categorias',
      description: 'Categorias de insumos.',
      icon: Tag,
    },
    {
      id: 'funcoes',
      label: 'Funções',
      shortLabel: 'Funções',
      href: '/configuracoes/funcoes',
      description: 'Funções e mão de obra.',
      icon: Users,
    },
    {
      id: 'maquinas',
      label: 'Máquinas',
      shortLabel: 'Máquinas',
      href: '/configuracoes/maquinas',
      description: 'Máquinas e equipamentos.',
      icon: Wrench,
    },
    {
      id: 'loja',
      label: 'Loja',
      shortLabel: 'Loja',
      href: '/configuracoes/loja',
      description: 'Configurações da loja.',
      icon: Building2,
    },
    {
      id: 'tipos-material',
      label: 'Tipos de material',
      shortLabel: 'Materiais',
      href: '/configuracoes/tipos-material',
      description: 'Tipos de material.',
      icon: Package,
    },
    {
      id: 'arte-aprovacao',
      label: 'Arte & Aprovação',
      shortLabel: 'Arte',
      href: '/configuracoes/arte-aprovacao',
      description: 'Precificação e fila de arte.',
      icon: Palette,
    },
    {
      id: 'conexoes',
      label: 'Hub de conexões',
      shortLabel: 'Conexões',
      href: '/configuracoes/conexoes',
      description: 'Google Drive, WhatsApp e integrações.',
      icon: Plug,
    },
    {
      id: 'validacoes',
      label: 'Validações automáticas',
      shortLabel: 'Validações',
      href: '/configuracoes/validacoes-automaticas/regras',
      description: 'Regras de validação automática.',
      icon: Shield,
    },
  ],
};
