import {
  BarChart3,
  ClipboardList,
  LayoutDashboard,
  Settings,
  User,
  Workflow,
} from 'lucide-react';
import type { ModuleNavConfig } from './types';

export const pcpModuleNav: ModuleNavConfig = {
  id: 'pcp',
  label: 'PCP',
  homeHref: '/pcp',
  items: [
    {
      id: 'visao-geral',
      label: 'Visão geral',
      shortLabel: 'Geral',
      href: '/pcp',
      description: 'Dashboard e atalhos do PCP.',
      icon: LayoutDashboard,
    },
    {
      id: 'kanban',
      label: 'Kanban',
      shortLabel: 'Kanban',
      href: '/pcp/kanban',
      description: 'Quadro de produção.',
      icon: ClipboardList,
    },
    {
      id: 'meu-setor',
      label: 'Meu setor',
      shortLabel: 'Meu setor',
      href: '/pcp/meu-setor',
      description: 'Fila e tarefas do setor.',
      icon: User,
    },
    {
      id: 'workflows',
      label: 'Workflows',
      shortLabel: 'Workflows',
      href: '/pcp/workflows',
      description: 'Fluxos de produção.',
      icon: Workflow,
    },
    {
      id: 'terceirizacao',
      label: 'Terceirização',
      shortLabel: 'Terceiros',
      href: '/pcp/terceirizacao',
      description: 'Serviços terceirizados.',
      icon: ClipboardList,
    },
    {
      id: 'apontamentos',
      label: 'Apontamentos',
      shortLabel: 'Apontamentos',
      href: '/pcp/apontamentos',
      description: 'Apontamentos de produção.',
      icon: ClipboardList,
    },
    {
      id: 'etapas',
      label: 'Etapas',
      shortLabel: 'Etapas',
      href: '/pcp/etapas',
      description: 'Cadastro de etapas.',
      icon: ClipboardList,
    },
    {
      id: 'relatorios',
      label: 'Relatórios',
      shortLabel: 'Relatórios',
      href: '/pcp/relatorios',
      description: 'Indicadores de produção.',
      icon: BarChart3,
    },
    {
      id: 'configuracao',
      label: 'Configuração',
      shortLabel: 'Config',
      href: '/pcp/configuracao',
      description: 'Ajustes do módulo PCP.',
      icon: Settings,
    },
  ],
};
