-- P1-5: tipar ordens_servico.status com enum StatusOS completo (16 valores).
-- Normaliza valores fora do enum para FILA antes do MODIFY.

UPDATE `ordens_servico`
SET `status` = 'FILA'
WHERE `status` IS NULL
   OR `status` NOT IN (
    'FILA',
    'AGUARDANDO_APROVACAO_FINANCEIRA',
    'AGUARDANDO_APROVACAO_TECNICA',
    'APROVADA_TECNICA',
    'AGUARDANDO_APROVACAO_ORCAMENTARIA',
    'APROVADA_ORCAMENTARIA',
    'REJEITADA',
    'LIBERADA_PARA_PCP',
    'PARCIALMENTE_LIBERADA',
    'EM_WORKFLOW',
    'PRODUCAO',
    'ACABAMENTO',
    'FINALIZADA',
    'CANCELADA',
    'AGUARDANDO_MATERIAL',
    'PAUSADA'
  );

ALTER TABLE `ordens_servico`
  MODIFY `status` ENUM(
    'FILA',
    'AGUARDANDO_APROVACAO_FINANCEIRA',
    'AGUARDANDO_APROVACAO_TECNICA',
    'APROVADA_TECNICA',
    'AGUARDANDO_APROVACAO_ORCAMENTARIA',
    'APROVADA_ORCAMENTARIA',
    'REJEITADA',
    'LIBERADA_PARA_PCP',
    'PARCIALMENTE_LIBERADA',
    'EM_WORKFLOW',
    'PRODUCAO',
    'ACABAMENTO',
    'FINALIZADA',
    'CANCELADA',
    'AGUARDANDO_MATERIAL',
    'PAUSADA'
  ) NOT NULL DEFAULT 'FILA';
