export enum ModalidadeExpedicao {
  RETIRADA_CLIENTE = 'RETIRADA_CLIENTE',
  ENTREGA_TRANSPORTADORA = 'ENTREGA_TRANSPORTADORA',
  ENTREGA_FROTA_PROPRIA = 'ENTREGA_FROTA_PROPRIA',
  INSTALACAO_NO_LOCAL = 'INSTALACAO_NO_LOCAL',
}
